---
- hosts:  all
  become: yes
  tasks:

    - name: get defaults
      include_vars:
        file: defaults/main.yml

    - name: clean rhel7 box internal repos
      file:
        path: /etc/yum.repos.d/pulp.repo
        state: absent

    - name: Subscribe to Red Hat
      redhat_subscription:
        state: present
        username: "{{ subs_username }}"
        password: "{{ subs_pw }}"
        autosubscribe: false
        pool: "{{ subs_pool }}"

    - name: Enable required repositories
      rhsm_repository:
        name: "{{ enabled_repos }}"
        state: enabled

    - name: Up it!
      package: name=* state=latest

    - name: install redhat nordics sa blog
      include_role:
        name: redhatnordicssa-blog
