# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "centos8" do |centos|
    centos.vm.hostname   = "centos8"
    centos.vm.box     = "centos/8"
    centos.vm.provision :ansible do |ansible|
      ansible.playbook = "../ansibles/prepare_centos8.yml"
    end
  end
  config.vm.provider "libvirt" do |lv|
    lv.memory = "1024"
  end
end
